fix: add missing binaries

diff --git a/.github/workflows/on-release.yaml b/.github/workflows/on-release.yaml
--- a/.github/workflows/on-release.yaml
+++ b/.github/workflows/on-release.yaml
@@ -138,6 +138,29 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: "Prepare dist directory"
+        run: |
+          mkdir -p dist/linux/amd64
+          mkdir -p dist/linux/arm64
+      - name: Download
+        uses: actions/download-artifact@v3
+        with:
+          name: bin-linux
+          path: dist/bin
+      - name: Unpack packages
+        run: |
+          [ -f ./dist/bin/${{ github.event.repository.name }}_*_arm64.tar.gz ] \
+          && tar -xvzf dist/bin/${{ github.event.repository.name }}_*_arm64.tar.gz -C dist/linux/arm64 \
+          || echo "archive arm64 not found" 
+          
+          [ -f ./dist/bin/${{ github.event.repository.name }}_*_x86_64.tar.gz ] \
+          && tar -xvzf dist/bin/${{ github.event.repository.name }}_*_x86_64.tar.gz -C dist/linux/amd64 \
+          || echo "archive x86_64 not found" 
+
+          [ -f ./dist/bin/${{ github.event.repository.name }}_*_amd64.tar.gz ] \
+          && tar -xvzf dist/bin/${{ github.event.repository.name }}_*_amd64.tar.gz -C dist/linux/amd64 \
+          || echo "archive amd64 not found" 
+
       - id: resolve-docker
         uses: actions/github-script@v6
         with:
